"""Scheduler — the cron plan (arch §8 cadences), print or install.

Cadence (all IST):
  06:00        morning build — catch-up scrape (incl. daily `top` feed), sync
               enrich, aggregate, score, drafts, compose, dispatch roundup
  07:00–00:00  hourly full pipeline (`run-local`); dispatch gates heads-up
               channel sends to 08:00–20:00 internally
  Sat 10:00    weekly compose + dispatch (Sat→Sat roundup)
  01:00–05:00  nothing — overnight pause (cursors catch up at 06:00)
"""
from __future__ import annotations

import subprocess
import sys

from community.config.settings import ROOT

MARK_BEGIN = "# >>> nubra-community-manager >>>"
MARK_END = "# <<< nubra-community-manager <<<"


def cron_block(docker: bool = False) -> str:
    """The crontab block. docker=True (`./cm schedule --docker`) emits the prod
    flavor where every pipeline command execs into the running api container
    (canonical hand-editable copy: deploy/crontab.prod)."""
    root = str(ROOT)
    run = "docker compose exec -T api flock -n /tmp/beacon.lock ./cm" if docker else "./cm"
    prelude = ("COMPOSE_PROFILES=app\nPATH=/usr/local/bin:/usr/bin:/bin\n"
               if docker else "")
    backup = (f"# 02:00 nightly DB backup (gzip pg_dump, keeps last 14)\n"
              f"0 2 * * * cd {root} && ./deploy/backup.sh >> out/cron.log 2>&1\n"
              if docker else "")
    return f"""{MARK_BEGIN}
# generated by `./cm schedule{' --docker' if docker else ''}` — cadences per architecture §8 (all IST)
{prelude}CRON_TZ=Asia/Kolkata
TZ=Asia/Kolkata
# hourly pipeline 07:00–00:59 IST (heads-up channel window 08–20 enforced in dispatch)
0 7-23 * * * cd {root} && {run} run-local >> out/cron.log 2>&1
0 0 * * * cd {root} && {run} run-local >> out/cron.log 2>&1
# 06:00 morning build (catch-up + daily top feed + sync enrich + roundup by 07:30)
0 6 * * * cd {root} && {run} morning-build >> out/cron.log 2>&1
# Saturday 10:00 weekly roundup (compose regenerates weekly row, dispatch sends once)
0 10 * * 6 cd {root} && {run} stage compose >> out/cron.log 2>&1 && cd {root} && {run} stage dispatch >> out/cron.log 2>&1
{backup}{MARK_END}"""


def show_or_install(install: bool | None = None) -> None:
    block = cron_block(docker="--docker" in sys.argv)
    if install is None:
        install = "--install" in sys.argv
    if not install:
        print(block)
        print("\n# To install into your crontab:  ./cm schedule --install"
              "\n# (or paste the block above via `crontab -e`)")
        return
    current = subprocess.run(["crontab", "-l"], capture_output=True, text=True).stdout
    if MARK_BEGIN in current:  # replace our block, keep everything else
        pre = current.split(MARK_BEGIN)[0]
        post = current.split(MARK_END)[-1]
        merged = pre.rstrip("\n") + "\n" + block + "\n" + post.lstrip("\n")
    else:
        merged = (current.rstrip("\n") + "\n\n" if current.strip() else "") + block + "\n"
    subprocess.run(["crontab", "-"], input=merged, text=True, check=True)
    print("crontab installed/updated — `crontab -l` to inspect")
